- server/src/ingestion.rs
- server/src/main.rs
This PR includes an Ingestor component that can connect to an MQTT broker, subscribe to specific topics and insert messages from these topics into the storage engine. It should be noted that this PR does not include unit tests since testing the ingestor requires an MQTT broker and simulator. This component should instead be tested as part of integration testing.
> Ingestion of MQTT messages.

- server/src/storage/data_point.rs
- server/src/storage/mod.rs
- server/src/storage/segment.rs
The previous version of the storage engine had the requirement that the amount of sensors outputting data into the system had to be constant and known before starting. This requirement has been removed so it is now possible to add and remove sensors while the system is running.
> Remove constant sensor count requirement.

- server/src/remote.rs
By implementing `do_put()`, data points can be pushed to the system using Apache Arrow Flight. Thus, any Apache Arrow Flight client should be supported. For example, the Python script below uses PyArrow to read an Apache Parquet file and transmit it to `127.0.0.1:9999`. By design, the implementation of `do_put()` assumes that the transmitted `RecordBatch`s has the same schema as the target table. The PR does purposely not include any unit tests as integration tests seemed more appropriate for `FlightServiceHandler` due to the infrastructure required to test it properly (Apache Arrow Flight server and client).
``` Python
import os
import sys
from pyarrow import parquet
from pyarrow import flight
if len(sys.argv) != 3:
print("usage: " + os.path.basename(__file__) + " table parquet-file") …
```
> Implement FlightServiceHandler.do_put()

- server/src/storage/data_point.rs
- server/src/storage/mod.rs
- server/src/storage/segment.rs
- server/src/storage/time_series.rs
This PR includes an extension to the functionality of the storage engine to avoid unnecessary I/O and very small files. Previously each compressed segment was saved in a separate Parquet file but now the storage engine stores the compressed data in memory if possible and saves compressed data in batches when necessary.
> Saving compressed segments together. 

- README.md
- server/src/catalog.rs
- server/src/main.rs
- server/src/remote.rs
- server/src/tables.rs
As the integration tests are not yet implemented, the code has been manually tested on Arch Linux, Ubuntu, and Windows 11. So for additional confirmation that the catalog is now compatible with Windows, please also manually check that tables are loaded and can be queried as expected. Finally, while some additional unit tests have been added, tests for functions and methods that operate on files were purposely not added to not duplicate work currently being done to effectively test IO in the storage engine.
> Refactor catalog and main

- Cargo.lock
- README.md
- client/Cargo.toml
- client/src/helper.rs
- client/src/main.rs
- server/Cargo.toml
- server/src/catalog.rs
- server/src/errors.rs
- server/src/ingestion.rs
- server/src/macros.rs
- server/src/main.rs
- server/src/models/gorilla.rs
- server/src/models/mod.rs
- server/src/models/pmcmean.rs
- server/src/models/swing.rs
- server/src/optimizer/mod.rs
- server/src/optimizer/model_simple_aggregates.rs
- server/src/remote.rs
- server/src/storage/data_point.rs
- server/src/storage/mod.rs
- server/src/storage/segment.rs
- server/src/storage/time_series.rs
- server/src/tables.rs
- server/src/types.rs
This PR should replace all instances of "MiniModelarDB" with "ModelarDB", "mmdbd" with "mdbd", and "mmdb" with "mdb" in preparation for renaming this repository to `ModelarDB-RS`. The README has also been updated to make it clear that this is the primary version of ModelarDB and that it superseeds the old [JVM-based](https://github.com/skejserjensen/ModelarDB) [version](https://github.com/ModelarData/ModelarDB).
> Rename MiniModelarDB to ModelarDB

- Cargo.lock
- README.md
- client/Cargo.toml
- client/src/helper.rs
- client/src/main.rs
- server/Cargo.toml
- server/src/catalog.rs
- server/src/errors.rs
- server/src/ingestion.rs
- server/src/macros.rs
- server/src/main.rs
- server/src/models/gorilla.rs
- server/src/models/mod.rs
- server/src/models/pmcmean.rs
- server/src/models/swing.rs
- server/src/optimizer/mod.rs
- server/src/optimizer/model_simple_aggregates.rs
- server/src/remote.rs
- server/src/storage/data_point.rs
- server/src/storage/mod.rs
- server/src/storage/segment.rs
- server/src/storage/time_series.rs
- server/src/tables.rs
- server/src/types.rs
Since reading from, writing to, and identifying Apache Parquet files is needed multiple places in the system, it was decided to add this functionality in the storage engine. This PR includes three new functions in the storage engine that allows interaction with Apache Parquet files. The functions are tested using the [tempfile](https://crates.io/crates/tempfile) crate that can create a temporary directory which is deleted once out of scope. 
The places in the storage engine and catalog that used their own versions of this Apache Parquet functionality has been replaced by the shared functionality. 
It should also be noted that two basic functions to retrieve the schemas used for uncompressed and compressed data has been added to the storage engine.
> General Apache Parquet functionality

- server/src/compression.rs
- server/src/main.rs
- server/src/models/gorilla.rs
- server/src/models/mod.rs
- server/src/models/pmcmean.rs
- server/src/models/swing.rs
This PR adds support for compressing univariate time series with regular timestamps (i.e., the data points are collected at a constant sampling interval). Support for compressing irregular time series and merging of similar models is planned but will be added through separate PRs to keep them at a manageable size. The compression is split across the new `compression` module and the `models` module. The `compression` module drives the compression by splitting the time series into dynamically sized segments, while the `models` module encodes the values and  selects the most efficient model for a dynamically sized segment.
> Add compression of regular time series

- client/src/main.rs
- server/src/remote.rs
This PR adds a temporary workaround for [issue \#2445 in arrow-rs](https://github.com/apache/arrow-rs/issues/2445) by extending [`FlightService.get_schema()`](https://github.com/ModelarData/ModelarDB-RS/blob/bug/serialize-schema/server/src/remote.rs#L178) to always prepend both the [32-bit continuation indicator and the 32-bit little-endian length](https://arrow.apache.org/docs/format/Columnar.html#encapsulated-message-format) to `SchemaResult.schema` so it can be deserialized by the other Apache Arrow Flight implementations. To preserve compatibility with the Rust client (`mdb`), [`execute_command()`](https://github.com/ModelarData/ModelarDB-RS/blob/bug/serialize-schema/client/src/main.rs#L192) have been extended to strip the first eight bytes of `SchemaResult.schema`. I have manually …
> Temporarily fix compatibility for SchemaResult

- Cargo.lock
- server/Cargo.toml
- server/src/catalog.rs
- server/src/main.rs
- server/src/remote.rs
This PR includes a new implementation of the `do_action` endpoint that adds support for two new actions; `CreateTable` and `CreateModelTable`. The `list_actions` endpoint has also been changed to reflect the new actions. Using a table name and a schema, a normal table can be created. This just creates an empty parquet file in the data folder to save the schema and table name.
Using a table name, schema, tag column indices and a timestamp column index, a model table can be created. This creates a new instance of the `NewModelTableMetadata` struct to save the data in the in-memory catalog and applies changes to the metadata SQLite tables to persist the new model table.
It should be noted that the old model table implementation has not been removed. This PR purely adds new functionality. It …
> Added actions to create table and create model table

- Cargo.lock
- README.md
- client/Cargo.toml
- client/src/main.rs
- server/Cargo.toml
- server/src/ingestion.rs
This PR renames the binaries from `mdbd` and `mdb` to `modelardbd` and `modelardb`.
> Rename the binaries to modelardbd and modelardb

- server/src/compression.rs
- server/src/models/bits.rs
- server/src/models/gorilla.rs
- server/src/models/mod.rs
- server/src/models/pmcmean.rs
- server/src/models/swing.rs
- server/src/models/timestamps.rs
- server/src/types.rs
This PR adds support for compressing irregular time series by implementing optimized methods for compressing the timestamps of segments from both regular and irregular time series. As the PR also splits `gorilla.rs` into `gorilla.rs`, `timestamps.rs` and `bits.rs` it may be easier to review the changes made to `BitReader` and `BitVecBuilder` by looking at the individual commits.
> Support compressing irregular time series

- server/src/compression.rs
- server/src/macros.rs
This PR adds a simple macro named [`get_array!()`](https://github.com/ModelarData/ModelarDB-RS/blob/dev/merge-segments/server/src/macros.rs#L24) for extracting and casting [`Array`s](https://docs.rs/arrow/latest/arrow/array/index.html) from a [`RecordBatch`](https://docs.rs/arrow/latest/arrow/record_batch/struct.RecordBatch.html) and a function named [`merge_segments`](https://github.com/ModelarData/ModelarDB-RS/blob/dev/merge-segments/server/src/compression.rs#L91) that merge segments with equivalent models stored in [`RecordBatch`](https://docs.rs/arrow/latest/arrow/record_batch/struct.RecordBatch.html).
> Merge segments with equivalent models

- server/src/main.rs
- server/src/storage/compressed_data_manager.rs
- server/src/storage/mod.rs
- server/src/storage/segment.rs
- server/src/storage/time_series.rs
- server/src/storage/uncompressed_data_manager.rs
This PR includes a minor change to the storage engine that makes it so we instead of queuing finished segments and making them available for retrieval, now just compress the segment directly. In the future this should be changed back and functionality should be added to a compression component that can dynamically allocate threads for compression. Each of these threads should retrieve finished segments from the storage engine and insert the compressed data back into the storage engine when done.
TODOs have been added to revert the storage engine when the above mentioned ideal functionality has been added. Finally, the PR contains a new field on the uncompressed data manager used to make the manager use the old functionality in the tests. This was only added to fix existing tests and …
> Compressing directly from storage engine

- Cargo.lock
- server/Cargo.toml
- server/src/catalog.rs
- server/src/compression.rs
- server/src/macros.rs
- server/src/main.rs
- server/src/models/gorilla.rs
- server/src/models/mod.rs
- server/src/models/pmcmean.rs
- server/src/models/swing.rs
- server/src/models/timestamps.rs
- server/src/optimizer/model_simple_aggregates.rs
- server/src/remote.rs
- server/src/storage/compressed_data_manager.rs
- server/src/storage/mod.rs
- server/src/storage/segment.rs
- server/src/storage/uncompressed_data_manager.rs
- server/src/tables.rs
- server/src/types.rs
The primary focus of this PR is to refactor the code in `table.rs` which adds support for querying model tables to Apache Arrow DataFusion. The `TODO`s that stated that a change should be made when `tables.rs` was refactored have also been fixed. However, a few of the broader `TODO`s have been rewritten and moved to a suitable location as the changes they suggested were not required for model tables to be queried and the changes they suggested would increase the size of this somewhat large PR. Multiple minor issues have also been fixed throughout the code base as they prevented model tables from being queried. Unfortunately, this PR also increases the time required to run all of the unit tests from 0.82s to 39.26s on my development VM as the buffers used by the storage engine have been …
> Refactor query engine

- server/src/models/mod.rs
- server/src/models/swing.rs
This PR extends Swing to also store if the minimum value was the first value in a segment or if the maximum value was the first value in a segment so the correct linear function can be reconstructed during query processing. The changed files contains some inconsistent code, e.g., they uses both `start_time` and `first_timestamp` as the name for the first timestamp in a segment, however, this was purposely not changed in this PR to keep it focused on fixing the problem in Swing.
> Fix Swing always using min value as first value

- Cargo.lock
- client/src/main.rs
- server/Cargo.toml
- server/src/compression.rs
- server/src/errors.rs
- server/src/main.rs
- server/src/metadata/mod.rs
- server/src/metadata/model_table_metadata.rs
- server/src/metadata/parser.rs
- server/src/models/mod.rs
- server/src/parser.rs
- server/src/remote.rs
- server/src/storage/compressed_data_manager.rs
- server/src/storage/mod.rs
- server/src/storage/uncompressed_data_manager.rs
This PR replaces the [`CreateTable`](https://github.com/ModelarData/ModelarDB-RS/blob/master/server/src/remote.rs#L545) and [`CreateModelTable`](https://github.com/ModelarData/ModelarDB-RS/blob/master/server/src/remote.rs#L552) Apache Arrow Flight [`Action`](https://docs.rs/arrow-flight/latest/arrow_flight/struct.Action.html)s with a single [`CommandStatementUpdate`](https://github.com/ModelarData/ModelarDB-RS/blob/dev/add-create-table-ddl/server/src/remote.rs#L512) which executes a SQL query containing a single command that produces no results. The use of a  single `Action` and the name `CommandStatementUpdate` was chosen to better match the current [Apache Arrow Flight SQL](https://arrow.apache.org/docs/format/FlightSql.html) specification, thus, hopefully making it simpler to switch to …
> Support CREATE MODEL TABLE DDL commands

- client/src/main.rs
- server/src/models/bits.rs
- server/src/models/mod.rs
- server/src/models/timestamps.rs
- server/src/optimizer/model_simple_aggregates.rs
This PR fixes a collection of minor issues that were discovered while experimenting with ingesting and querying irregular time series with one issue fixed per commit. The addition of `count` to `ModelSumAccumulator` is required to match [`SumAccumulator`](https://github.com/apache/arrow-datafusion/blob/master/datafusion/physical-expr/src/aggregate/sum.rs#L138)  but it is unclear what the purpose of `count` in `SumAccumulator` is and its value seems to have no effect on the result. The files have purposely only been changed to the degree necessary to fix the bugs.
> Fix bugs caused by irregular time series

- server/src/main.rs
- server/src/metadata/mod.rs
- server/src/remote.rs
To simplify the process of passing the tokio runtime to sub-components, the runtime has been removed from the context. This means that instead of retrieving the runtime from the context, components that need to carry out async tasks need to receive a reference to the runtime that is created in main. 
Currently there is no large benefit to this change but the need for it becomes more clear when components that rely on the async object_store crate are added (fx. data transfer).
> Removed tokio runtime from context

- .github/workflows/cargo-test-on-pr.yml
- README.md
This PR updates the version of Microsoft Windows used in GitHub Actions as [snmalloc](https://github.com/microsoft/snmalloc/blob/main/docs/BUILDING.md#building-on-windows) no longer lists Visual Studio 2017 as a supported version and now lists Visual Studio 2022 as a supported version.
> Update Microsoft Windows in CI

- Cargo.lock
- server/Cargo.toml
- server/src/main.rs
- server/src/metadata/mod.rs
- server/src/storage/compressed_data_manager.rs
- server/src/storage/data_transfer.rs
- server/src/storage/mod.rs
- server/src/storage/time_series.rs
This PR includes a new component to handle transferring compressed data to a remote object store. It should be noted that the data transfer component is working and tested separately but it is not yet included in the flow of the complete system. This is mainly due to the data transfer component currently using `runtime.block_on` which cannot be used from within the storage engine since the storage engine is invoked from an async function (`do_put`).
When the storage engine has been made async, the data transfer component can also be made async and can then be included in the complete data flow.
> Added data transfer component

- server/src/main.rs
- server/src/metadata/mod.rs
- server/src/remote.rs
- server/src/storage/compressed_data_manager.rs
- server/src/storage/data_transfer.rs
- server/src/storage/mod.rs
This PR removed all use of the Tokio runtime within the data transfer component (previously used for `runtime.block_on()`) and converts the data transfer component to instead use async/await. This means that the data transfer component can now be invoked from another async function, such as from the Arrow flight endpoints. 
Further, the PR also adds a new action to make it possible to flush the entire edge. This action first flushes uncompressed memory to disk and then flushes all compressed data saved on disk to the remote store if possible.
> Made data transfer async and added action to flush the edge

- server/src/main.rs
- server/src/metadata/mod.rs
- server/src/remote.rs
- server/src/storage/data_transfer.rs
- server/src/storage/mod.rs
- server/src/storage/uncompressed_data_buffer.rs
- server/src/storage/uncompressed_data_manager.rs
This PR replaces [`ParquetRecordBatchReader`](https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.ParquetRecordBatchReader.html) with the async [`ParquetRecordBatchStream`](https://docs.rs/parquet/latest/parquet/arrow/async_reader/struct.ParquetRecordBatchStream.html) in [`StorageEngine.read_batch_from_apache_parquet_file()`](https://github.com/ModelarData/ModelarDB-RS/blob/dev/storage-async/server/src/storage/mod.rs#L311) and moves creation of [`DataTransfer`](https://github.com/ModelarData/ModelarDB-RS/blob/dev/storage-async/server/src/storage/data_transfer.rs) to [`StorageEngine::try_new()`](https://github.com/ModelarData/ModelarDB-RS/blob/dev/storage-async/server/src/storage/mod.rs#L96). The scope of this PR was initially to make reading from and writing to local storage …
> Use ParquetRecordBatchStream in StorageEngine

- server/src/storage/data_transfer.rs
- server/src/storage/mod.rs
This PR configures [ArrowWriter](https://docs.rs/parquet/latest/parquet/arrow/arrow_writer/struct.ArrowWriter.html) with the global [WriterProperties](https://docs.rs/parquet/latest/parquet/file/properties/struct.WriterProperties.html) that currently provides the best trade-off between ingestion time, query time, and the amount of storage required according to an extensive search performed by [Evaluate-ModelarDB-Changes](https://github.com/ModelarData/Utilities/tree/main/Evaluate-ModelarDB-Changes) using a 1 GiB real-life data set, a 63 MiB real-life data set, and simple aggregate queries that aggregate the entire ingested data set. The following tables shows the set of nondominated results as computed by this [Python script](https://github.com/matthewjwoodruff/pareto.py). The …
> Use optimized settings for ArrowWriter

- Cargo.lock
- server/Cargo.toml
- server/src/compression.rs
- server/src/models/mod.rs
- server/tests/integration_test.rs
This pull request adds a generator for generating random test data and randomized irregular timestamps, new tests for testing irregular time series during compression, and a test to ensure that the selected model has the least amount of bytes. Additional fixes for the macOS and Windows testing environments have also been added to (hopefully) ensure that GitHub checks do not fail again on these platforms.
> Add irregular time series testing and randomly generated data to current tests.

- Cargo.lock
- server/Cargo.toml
- server/src/metadata/mod.rs
- server/src/remote.rs
- server/src/storage/compressed_data_manager.rs
- server/src/storage/data_transfer.rs
- server/src/storage/mod.rs
- server/src/storage/uncompressed_data_buffer.rs
- server/src/storage/uncompressed_data_manager.rs
- server/src/types.rs
This PR includes changes to the storage engine and API to support collecting internal statistics and retrieving them through the Arrow Flight API. Data on the used compressed and uncompressed memory is recorded every time the remaining reserved memory is changed. When uncompressed data is spilled to disk or when compressed files are saved to disk, the used disk space is recorded. Finally, every time a batch of data points is ingested, the number of data points are recorded.
> Collect internal statistics

- .github/workflows/cargo-build-lint-and-test-on-pr-and-push.yml
- .github/workflows/python-unittest-on-pr-and-push.yml
- .gitignore
- Cargo.toml
- crates/modelardb_client/Cargo.toml
- crates/modelardb_common/Cargo.toml
- crates/modelardb_compression/Cargo.toml
- crates/modelardb_compression/src/lib.rs
- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_compression_python/Cargo.toml
- crates/modelardb_compression_python/build.rs
- crates/modelardb_compression_python/pyproject.toml
- crates/modelardb_server/Cargo.toml
- crates/modelardb_server/tests/integration_test.rs
This PR fixes three minor unrelated issues: (1) add missing license headers, (2) use `generate_values()` for testing compression, and (3) specify the minimum version of `maturin` to silence warnings.
> Fix headers, integration test, and warnings

- Cargo.lock
- crates/modelardb_common/src/macros.rs
- crates/modelardb_compression/src/lib.rs
- crates/modelardb_compression/src/models/swing.rs
- crates/modelardb_compression_python/src/lib.rs
- crates/modelardb_server/Cargo.toml
- crates/modelardb_server/src/metadata/mod.rs
- crates/modelardb_server/src/metadata/model_table_metadata.rs
- crates/modelardb_server/src/parser.rs
- crates/modelardb_server/src/query/grid_exec.rs
- crates/modelardb_server/src/query/sorted_join_exec.rs
- crates/modelardb_server/src/remote.rs
- crates/modelardb_server/src/storage/compressed_data_buffer.rs
- crates/modelardb_server/src/storage/compressed_data_manager.rs
- crates/modelardb_server/src/storage/data_transfer.rs
- crates/modelardb_server/src/storage/mod.rs
- crates/modelardb_server/src/storage/uncompressed_data_buffer.rs
- crates/modelardb_server/src/storage/uncompressed_data_manager.rs
This PR resolves a set of issues with the current ingestion and query processing pipeline. Specifically it:
- Makes [`merge_segments()`](https://github.com/ModelarData/ModelarDB-RS/blob/f6d7b0ee0c6991b87b0044f5112e18d7dbe04417/crates/modelardb_compression/src/lib.rs#L97) compatible with the  query processing pipeline by only merging segments that are from the same time series and adjacent in time.
- Fixes an issue with queries returning an incorrect number of data points for a model table due to an offset not being reset correctly.
- Makes the query processing pipeline compatible with  [`DataTransfer`](https://github.com/ModelarData/ModelarDB-RS/blob/f6d7b0ee0c6991b87b0044f5112e18d7dbe04417/crates/modelardb_server/src/storage/data_transfer.rs#L44) by not assuming each column of a model …
> Resolve issues with ingestion and processing

- crates/modelardb_server/src/storage/uncompressed_data_buffer.rs
- crates/modelardb_server/src/storage/uncompressed_data_manager.rs
This PR makes the `UncompressedDataManager` finish in-memory data buffers that are no longer used by tracking how many `RecordBatch`es has been received and which `RecordBatch` caused data points to be added to each in-memory data buffer. This reduces the amount of memory required when bulk-loading as there is no need to keep an open buffer for a time series after all of the data points for it has been loaded. At the end of `UncompressedDataManager::insert_data_points()` the buffers that have not been updated by the current batch is finished and thus compressed to release memory for additional uncompressed data points. For simplicity `UncompressedDataManager::insert_data_points()` currently perform the check after ingesting each `RecordBatch`, so as part of optimizing the storage engine a …
> Automatically finish unused in-memory buffers

- Cargo.lock
- README.md
- crates/modelardb_server/Cargo.toml
- crates/modelardb_server/src/main.rs
- crates/modelardb_server/src/storage/compressed_data_manager.rs
- crates/modelardb_server/src/storage/data_transfer.rs
This PR includes changes to make it possible to change the server port using an environment variable. `9999` is still used as the default port but it is now possible to overwrite this default with a custom port.
> Now possible to change the server port with an environment variable

- README.md
- crates/modelardb_client/src/main.rs
- crates/modelardb_server/src/main.rs
This PR adds support for other ports than 9999 to the client by allowing a non-default port to be specified using the syntax `host:port`.
> Support other ports than 9999 in the client

- crates/modelardb_common/src/schemas.rs
- crates/modelardb_compression/src/lib.rs
- crates/modelardb_compression/src/models/gorilla.rs
- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_compression/src/models/pmc_mean.rs
- crates/modelardb_compression/src/models/swing.rs
- crates/modelardb_compression_python/tests/__init__.py
This PR modifies the compression in two ways. First, the size of the metadata is now included when computing the number of bytes per value a model requires, e.g., a single segment of length eight is better than two segments of length four due to the metadata. Second, Gorilla is no longer evaluated alongside PMC-Mean and Swing, instead it is used as a fallback when neither PMC-Mean nor Swing can create models that efficiently encode a sub-sequence of values. Another benefit of only using Gorilla for values is that PMC-Mean and Swing cannot compress, is that the length bound is no longer needed. Preliminary results indicates that this reduces the amount of storage required by 5-25% by using PMC-Mean and Swing for more values and decreases ingestion speed by 0-10% .
> Evaluate PMC-Mean and Swing before Gorilla

- README.md
- crates/modelardb_server/src/main.rs
- crates/modelardb_server/src/remote.rs
- docs/user/README.md
This PR makes it possible to use Azure Blob Storage when starting the server with the `object_store_type://bucket_name` syntax for the argument. Since both S3 and Azure Blob Storage object stores now need to be validated when we start the server, the previous check function was also replaced by a generalized version that is used both when starting the server and when updating the remote object store using the action.
> Support for Azure Blob Storage as initial remote data folder

- crates/modelardb_compression/src/lib.rs
- crates/modelardb_compression/src/models/gorilla.rs
- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_compression/src/models/pmc_mean.rs
This PR adds preliminary support for lossy compression to Gorilla by changing the current value to the previous value if possible within the error bound. Experiments showed that this can reduce the amount of storage required by up to 22%. I also tried rewriting the current value to be as close as possible numerically to the previous value if the current value cannot be reduced to the previous value within the error bound. However, this increased the amount of stored by up to  2.6% compared to only rewriting the current value if it is within the error bound of the previous value. It is probably possible to rewrite the current value to produce the smallest result when XOR'ed with the previous value, however, this would require a significant amount of work that probably cannot be reused if …
> Rewrite value if within error bound in Gorilla

- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_compression/src/models/pmc_mean.rs
- crates/modelardb_compression/src/models/swing.rs
- crates/modelardb_server/src/metadata/mod.rs
This PR explicitly restrict `ErrorBound` to percentage values from 0% to 100% in order to improve error messages.
> Restrict ErrorBound to 0-100 to improve errors

- crates/modelardb_common/src/macros.rs
- crates/modelardb_common/src/schemas.rs
- crates/modelardb_compression/src/lib.rs
- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_compression/src/models/swing.rs
- crates/modelardb_compression_python/src/lib.rs
- crates/modelardb_server/src/optimizer/model_simple_aggregates.rs
- crates/modelardb_server/src/query/grid_exec.rs
- crates/modelardb_server/src/storage/data_transfer.rs
- crates/modelardb_server/src/storage/mod.rs
This PR makes the compression store the values in short Gorilla segments as part of the previous segment if any exists. As each segment contains a significant amount of metadata can short segments require more storage than the uncompressed timestamps and values. Small scale experiments show that the changes in this PR reduce the amount of storage required from 2.6% to 10.5%. The amount of storage can be further reduced by not storing the first value in full for these residual values and instead computing the XOR to the last value represented by the model in the segment, however, this is not done in this PR as it will require some refactoring of `crates/modelardb_compression/src/models/gorilla.rs` and thus make the smaller changes in this PR harder to review.
> Store short segments in previous segment

- .github/workflows/cargo-build-lint-and-test-on-pr-and-push.yml
This PR uses GitHub Actions to compute code coverage for all crates in the repository using [LLVM's instrumentation-based coverage](https://doc.rust-lang.org/rustc/instrument-coverage.html) and then [grcov](https://github.com/mozilla/grcov) to produce a HTML report which is attached to the workflow run as an [artifact with a 90 days retention period](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts). A minor limitation of this approach is that the small number of Python unit test in repository is not included. GitHub does not seem to support [visualization code coverage like GitLab](https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html), so it seems necessary to either [post comments with Markdown on …
> Compute code coverage for all OSes

- Cargo.toml
- crates/modelardb_client/Cargo.toml
- crates/modelardb_common/Cargo.toml
- crates/modelardb_compression/Cargo.toml
- crates/modelardb_compression_python/Cargo.toml
- crates/modelardb_server/Cargo.toml
Inspired by [Apache Arrow DataFusion](https://github.com/apache/arrow-datafusion/blob/main/Cargo.toml), this PR moves the [specification of the dependencies to the workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) to ensure each component uses the same versions and to make it simpler to update them. Features are still defined in the `Cargo.toml` file for each component as the features each component use sometimes differ. In addition, it adds [Cargo's default `release` profile ](https://doc.rust-lang.org/cargo/reference/profiles.html#release) as `dev-release`  as `release` is already used for [Apache Arrow DataFusion's optimized configuration](https://arrow.apache.org/datafusion/user-guide/example-usage.html#optimized-configuration) to ensure `cargo …
> Add workspace packages and dev-release profile

- crates/modelardb_server/src/optimizer/model_simple_aggregates.rs
- crates/modelardb_server/src/query/generated_as_exec.rs
- crates/modelardb_server/src/query/grid_exec.rs
- crates/modelardb_server/src/query/mod.rs
- crates/modelardb_server/src/query/sorted_join_exec.rs
- crates/modelardb_server/tests/integration_test.rs
As Apache Arrow DataFusion's optimizer rules has been re-enabled by #101, this PR updates the metadata returned by each  [`ExecutionPlan`](https://docs.rs/datafusion/latest/datafusion/physical_plan/trait.ExecutionPlan.html) added to Apache Arrow DataFusion in `modelardbd`. This is to ensure Apache Arrow DataFusion's optimizer knows which optimizations are possible, and more importantly, safe. For example, n * [`ParquetExec` -> `GridExec` -> `PartitionExec`] -> `SortedJoinExec` is not safe as far as I can tell since the documentation for [`ExecutionPlan::required_input_ordering()`](https://docs.rs/datafusion/latest/datafusion/physical_plan/trait.ExecutionPlan.html#method.required_input_ordering) states that it _"Specifies the ordering requirements for all of the children. For each child, …
> Fix the operator metadata used for planning

- crates/modelardb_server/src/query/generated_as_exec.rs
This PR adds the column name and row to the error message that are returned if the values for a generated column cannot be generated, e.g., if the [PhysicalExpr](https://docs.rs/datafusion-physical-expr/latest/datafusion_physical_expr/trait.PhysicalExpr.html) divides by zero. Unfortunately, as far as I can tell, it is not possible to extract which row caused the error from [PhysicalExpr](https://docs.rs/datafusion-physical-expr/latest/datafusion_physical_expr/trait.PhysicalExpr.html), [DataFusionError](https://docs.rs/datafusion/latest/datafusion/error/enum.DataFusionError.html), or [ArrowError](https://docs.rs/arrow-schema/38.0.0/arrow_schema/enum.ArrowError.html). So the method `GeneratedAsStream::failing_row()` has been added which tries to evaluate the failed …
> Improve runtime errors for generated columns

- crates/modelardb_server/src/remote.rs
This PR increases the size of gRPC messages that `modelardbd` accepts to from 4 MiB to 16 MiB (chosen because [Apache Arrow Ballista used it](https://github.com/apache/arrow-ballista/commit/10e021a9a3fcdc1a5c07c89737f3c2bb33cc1b7d)). This is simplifies use of the Python scripts in [ModelarData/Utilities](https://github.com/ModelarData/Utilities) as `pyarrow` does not seem to limit the message size by default and setting [`pyarrow.flight.FlightClient.write_size_limit_bytes`](https://arrow.apache.org/docs/python/generated/pyarrow.flight.FlightClient.html) to 4 MiB to match the default value of [`max_decoding_message_size`](https://docs.rs/arrow-flight/latest/arrow_flight/flight_service_server/struct.FlightServiceServer.html#method.max_decoding_message_size) in …
> Increase the size of gRPC messages supported

- crates/modelardb_server/src/parser.rs
- crates/modelardb_server/tests/integration_test.rs
This PR adds the requirement that the expression used to generate a column must be surrounded by parentheses to more closely match RDBMs like [MySQL](https://dev.mysql.com/doc/refman/8.0/en/create-table-generated-columns.html) and [PostgreSQL](https://www.postgresql.org/docs/current/ddl-generated-columns.html).
> AS must be followed by (expr) to match RDBMSs

- crates/modelardb_compression/src/types.rs
This PR corrects a typo in `CompressedSegmentBuilder::update_values_for_swing()` by replacing `residuals_min_value < self.min_value && self.max_value < residuals_min_value` with `residuals_min_value < self.min_value && self.max_value < residuals_max_value` such that segments containing a model of type Swing is stored correctly even if the residuals includes both the segment's minimum and maximum value. To decrease that chance that more issues in the code the encodes and decodes models exists, the amount of unit tests for this code has also been significantly increased.
> Fix wrong comparison when encoding of Swing

- Cargo.lock
- Dockerfile
- README.md
- crates/modelardb_server/Cargo.toml
- docs/user/README.md
This PR replaces CMake with the `cc` crate, thus CMake is no longer needed to build the system. The documentation has also been updated to reflect this. As the GitHub Action Runners all include CMake, the changes has been manually tested on FreeBSD, Linux, macOS, and Microsoft Windows systems without CMake.
> Replace CMake with cc and update docs

- docs/user/README.md
This PR updates the installation instructions to make it clear that Microsoft Visual C++ (MSVC) and Python 3 is required to build all of the crates in the project on Microsoft Windows. Since the MSVC components the `rustup` book states should be installed before the MSVC-based Rust toolchain can be used on Microsoft Windows are sufficient to compile all creates in the proejct, our simple installation instructions have been replaced with a link to the much more detailed instructions in the `rustup` book.
> Update the installation guide for Windows

- Cargo.lock
- crates/modelardb_server/Cargo.toml
- crates/modelardb_server/src/metadata/mod.rs
This PR adds support for storing metadata about the Apache Parquet files that the storage engine creates for storing the compressed segments. By storing the metadata in the metadata database instead of in the file names, multiple file operations can be performed atomically as the files are first accessible when their metadata has been written to the metadata database. To significantly simplify retrieving files based on their time and value range, the special floating-point values are rewritten to their closets normal floating value by `rewrite_special_value_to_normal_value(value: Value)` before they are stored in the metadata database. While this reduces the metadata managers ability to prune away files slightly, e..g, `NaN` and `f32::MAX` becomes the same value, it seems to be uncommon …
> Support storing metadata for files in database

- crates/modelardb_common/src/errors.rs
- crates/modelardb_common/src/schemas.rs
- crates/modelardb_common/src/types.rs
- crates/modelardb_server/src/common_test.rs
- crates/modelardb_server/src/configuration.rs
- crates/modelardb_server/src/main.rs
- crates/modelardb_server/src/metadata/mod.rs
- crates/modelardb_server/src/remote.rs
- crates/modelardb_server/src/storage/compressed_data_manager.rs
- crates/modelardb_server/src/storage/mod.rs
- crates/modelardb_server/src/storage/uncompressed_data_manager.rs
- crates/modelardb_server/tests/integration_test.rs
This PR includes a new separate server configuration component. The configuration has been moved out of the metadata manager and the new component has been added to the context so it is still available to the rest of the system. The configuration component also includes setters for the uncompressed and compressed reserved memory. Since they affect the remaining memory in the storage engine, setters have also been added to the storage managers. Finally, the PR also includes some new actions to get and update the configuration and integration/unit tests for the new functionality.
> Server configuration component

- crates/modelardb_compression/src/merge.rs
- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_compression/src/models/swing.rs
- crates/modelardb_compression/src/types.rs
- crates/modelardb_server/src/common_test.rs
- crates/modelardb_server/src/storage/data_transfer.rs
- crates/modelardb_server/src/storage/uncompressed_data_manager.rs
This PR changes the code that merges segments to determine if models can be merged based on their decoded coefficients instead of their encoded representation stored in the segments. This is necessary as models with the same encoded representation is not guaranteed to produce the same values while models with the same decoded coefficients are. In addition it removes the attempt to merge segments in newly compressed batches as adjacent segments with equivalent models should never be produced by the compression.
> Fix incorrect merging of models

- docs/user/README.md
This PR extends docs/userREADME by adding examples of \d, \dt, and SQL to the section Execute SQL as \d and \dt was not documented.
> Add \d, \dt, and SQL to user README Execute SQL

- Cargo.lock
- crates/modelardb_common/Cargo.toml
- crates/modelardb_common/src/arguments.rs
- crates/modelardb_manager/src/main.rs
- crates/modelardb_server/src/main.rs
This PR fixes a bug that made it possible to start the server with an Azure Blob Storage object store with valid connection information but an invalid container name. Object stores are now only seen as valid if the connection information is correct and the container/bucket exists. 
Since it is no longer necessary to pass the remote data folder type, the struct has been removed as well as the corresponding utility function. Furthermore, since the interface is simpler, the server now also validates the object store it receives from the manager if started in `MultiNode` mode.
> Fixed validation of Azure Blob Storage object stores

- crates/modelardb_server/tests/integration_test.rs
This PR adds a few integration tests to the actions `CollectMetrics` and `UpdateConfiguration`/`GetConfiguration`. These actions were previously not tested properly since the actions return the response in raw bytes and we were not able to find a method to read these bytes into a record batch. 
This PR adds a method to do this and adds a few tests that use this method to finally test the actions.
> New integration tests for existing actions

- crates/modelardb_compression_python/README.md
- docs/dev/README.md
- docs/user/README.md
This PR fixes a link in the user documentation that linked to a file in the repository that did not exist. It also makes some links to files in the repository use a local path instead of using the `Github` path. This makes it a bit more future proof since the links will not break if the repository host is moved and it also ensures that we link to the files in the current branch and not always the master branch.
> Fixed broken documentation link and made other links local

- crates/modelardb_server/src/storage/compressed_data_buffer.rs
- crates/modelardb_server/src/storage/compressed_data_manager.rs
- crates/modelardb_server/src/storage/mod.rs
- crates/modelardb_server/src/storage/uncompressed_data_manager.rs
This PR fixes minor consistency errors in `StorageError`. Thus, the PR purposely converts the two functions in `storage/mod.rs` into methods on `StorageEngine` as it required the smallest amount of changes to make the implementation of sub-routines that do not have a `self` parameter consistent in `StorageEngine`.
> Fix minor consistency errors in StorageEngine

- crates/modelardb_compression/src/merge.rs
- crates/modelardb_server/src/storage/uncompressed_data_buffer.rs
This PR makes `UncompressedDataBuffer.record_batch()` always return a `RecordBatch` sorted by time to support out-of-order data points. As all `FIELD` and `TAG` columns in a `MODEL TABLE` shares the timestamps and each ingested data point must contain a value for all columns (i.e., `NULL` values cannot occur), sorting each `UncompressedDataBuffer` by time should always preserve the global sort order required for query processing.
> Add sorting by time to UncompressedDataBuffer

- crates/modelardb_server/src/storage/compressed_data_buffer.rs
- crates/modelardb_server/src/storage/uncompressed_data_buffer.rs
This PR makes it possible to run `cargo test` with `--release` in addition development builds by excluding tests that checks for `debug_assert!()` from `--release` builds.
> Remove test of debug_assert!() from --release

- crates/modelardb_compression/src/models/timestamps.rs
This PR changes the number of bits used for the first delta when compressing timestamps from 14-bits to 24-bits so the delta can represent a delta of more than 4 hours as stated in the comment.
> Use 24-bits for first timestamp delta

- crates/modelardb_common/src/test/data_generation.rs
- crates/modelardb_compression/src/compression.rs
- crates/modelardb_compression/src/lib.rs
- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_compression/src/models/swing.rs
- crates/modelardb_server/src/optimizer/model_simple_aggregates.rs
- crates/modelardb_server/src/storage/types.rs
- crates/modelardb_server/tests/integration_test.rs
This PR makes the integrations tests more realistic by creating multiple `FIELD` columns for each table and adds support for generating multivariate time series to be ingested into them. In addition, all simple aggregates are now tested and additional asserts have been added to ensure one query is actually executed on data points and one query is executed on segments. These tests found a few issues regarding the implementation of `SUM()` on segments which have been fixed.
> Add integration tests and fix aggregattion

- crates/modelardb_compression/src/models/gorilla.rs
- crates/modelardb_compression/src/models/mod.rs
This PR fixes a bug in `Gorilla:::sum()` which caused the method to try and read past the end of the buffer containing the compressed data due to the variable containing the index to stop at having underflowed. In addition, multiple tests have been added to prevent this from happening again in the future.
> Fix gorilla::sum() underflow

- crates/modelardb_server/src/manager.rs
This PR makes it possible to set the IP address of the ModelarDB server using the environment variable `MODELARDBD_IP_ADDRESS`.
> Now possible to set IP address with environment variable

- crates/modelardb_common/src/arguments.rs
- crates/modelardb_common/src/test/mod.rs
- crates/modelardb_compression/src/models/gorilla.rs
- crates/modelardb_manager/src/remote.rs
- crates/modelardb_server/src/configuration.rs
- crates/modelardb_server/src/main.rs
- crates/modelardb_server/src/manager.rs
- crates/modelardb_server/src/query/mod.rs
- crates/modelardb_server/src/remote.rs
- crates/modelardb_server/src/storage/compressed_data_manager.rs
- crates/modelardb_server/src/storage/data_transfer.rs
- crates/modelardb_server/src/storage/mod.rs
For simplicity, access to the remote metadata database was handled in the same way for both cloud nodes and edge nodes which meant both technically had access to it. However, edge nodes never used this access since the local metadata database is used for querying and transfer of metadata is handled through the manager. 
To make the system both more secure (connection information is no longer transferred if not necessary) and more scalable (fewer connections to the remote metadata database) access has been removed for edge nodes.
> Edge nodes no longer have access to the remote metadata database

- crates/modelardb_compression/src/lib.rs
- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_server/src/query/grid_exec.rs
This PR makes `GridStream` collect relevant metrics that is shown when `EXPLAIN ANALYZE` is used. Are there any other metrics that are efficient to compute and relevant to add?
> Collect relevant metrics in GridStream

- crates/modelardb_common/src/test/data_generation.rs
- crates/modelardb_compression/src/models/bits.rs
- crates/modelardb_compression/src/models/gorilla.rs
- crates/modelardb_compression/src/models/timestamps.rs
This PR modifies the Gorilla-based timestamp compression so it store all residual timestamps as a bit prefix which indicates a size and a delta-of-delta. This allows all residual timestamps to be stored using an appropriate number of bites without the possibility of overflow which could happen when using 14 bits for the first residual timestamp as described in the Gorilla paper. In addition it simplifies the code to store the first residual timestamp as a delta-of-delta like all the other timestamp instead of a delta like in the Gorilla paper. To compute a delta-of-delta for the second timestamp a hard coded second delta with the value zero is used.
> Prevent timestamp compression from overflowing

- crates/modelardb_common/Cargo.toml
- crates/modelardb_common/src/lib.rs
- crates/modelardb_common/src/metadata/mod.rs
- crates/modelardb_common/src/parser.rs
- crates/modelardb_common/src/storage.rs
- crates/modelardb_server/src/context.rs
- crates/modelardb_server/src/storage/compressed_data_buffer.rs
- crates/modelardb_server/src/storage/compressed_data_manager.rs
- crates/modelardb_server/src/storage/data_transfer.rs
- crates/modelardb_server/src/storage/mod.rs
- crates/modelardb_server/src/storage/uncompressed_data_buffer.rs
This PR fixes a bug that caused Apache Parquet files to not always be read fully. We now loop over the batches in the file until the entire file is read. Duplicated code between `merge_compressed_apache_parquet_files` and `read_batch_from_apache_parquet_file` has been removed using a utility function and the read/write functions and the utility functions have been moved to `modelardb_common` so they can be used everywhere (including Library). 
Since the read/write Parquet functions have been moved, the storage engine now no longer has any associated functions and now only has methods.
It should be noted that reading batches in the Apache Parquet files using concurrency was researched but due to issues with the batches getting read out of order and therefore resulting in an out of order …
> Now always reading the full Apache Parquet file when reading record batches

- crates/modelardb_common/src/storage.rs
- crates/modelardb_server/src/storage/uncompressed_data_buffer.rs
This PR changes the `data page` size and `row group` size for [Apache Parquet](https://parquet.apache.org/docs/file-format/) files storing compressed segments containing metadata and models based on the results below. The `data page` size is reduced from [1,048,576](https://arrow.apache.org/rust/parquet/file/properties/constant.DEFAULT_PAGE_SIZE.html) to 16,384 and the `row group` size is reduced from [1,048,576](https://arrow.apache.org/rust/parquet/file/properties/constant.DEFAULT_MAX_ROW_GROUP_SIZE.html) to 65,536. These values provided the best trade-off between ingestion time, compaction time, query time for different query types, and the amount of storage required according to an extensive search performed by [Evaluate-ModelarDB-Changes](https://github.com/ModelarData/Utilities/tree/ …
> Optimize Apache Parquet page and row group sizes

- crates/modelardb_common/src/metadata/mod.rs
- crates/modelardb_common/src/metadata/model_table_metadata.rs
- crates/modelardb_common/src/parser.rs
- crates/modelardb_common/src/test/data_generation.rs
- crates/modelardb_common/src/test/mod.rs
- crates/modelardb_common/src/types.rs
- crates/modelardb_compression/src/compression.rs
- crates/modelardb_compression/src/lib.rs
- crates/modelardb_compression/src/merge.rs
- crates/modelardb_compression/src/models/gorilla.rs
- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_compression/src/models/pmc_mean.rs
- crates/modelardb_compression/src/models/swing.rs
- crates/modelardb_compression/src/types.rs
- crates/modelardb_server/src/storage/compressed_data_manager.rs
- crates/modelardb_server/tests/integration_test.rs
- docs/user/README.md
This PR add support for an absolute error bound in addition to the existing relative error bound. This is done by changing `ErrorBound` from a `struct` to an `enum` with two implementations and moving the code in `swing.rs` that computed the maximum allowed difference to `models/mod.rs`. Thus, all of the code that works directly with the error bounds is now in `models/mod.rs` and by using an `enum` instead of a `struct` with a flag, `rustc` refuses to compile code that does handle both of the error bounds. While the PR is very large, the majority of it is tests.
> Add support for an absolute error bound

- crates/modelardb_server/src/storage/compressed_data_manager.rs
- crates/modelardb_server/src/storage/types.rs
- crates/modelardb_server/src/storage/uncompressed_data_manager.rs
This PR removes the "free_memory" methods for multivariate, uncompressed, and compressed data since the functionality of the methods are covered by the corresponding "adjust_memory" methods.
> Removed duplicated functionality from MemoryPool

- crates/modelardb_compression/src/models/swing.rs
- crates/modelardb_server/src/main.rs
- crates/modelardb_server/src/optimizer/model_simple_aggregates.rs
Implementation of recording mechanism for Swing (Section 3.2 in Swing and Slide paper) to minimize MSE. The mechanism generated slightly lower Mean Squared Error and Mean Absolute Percentage Error than the current approach when tested with real-life datasets. However, its improvement over the current approach is not absolute and it varies depending on data points' properties.
> Add support for Swing's recording mechanism for minimum MSE

- crates/modelardb_common/src/storage.rs
- crates/modelardb_server/src/context.rs
- crates/modelardb_server/src/storage/mod.rs
This PR renames the data folder "uncompressed" to "buffers" and "compressed" to "tables" so their names better represent the data they contain. Only the name of the folders have purposely been changed to keep the terminology in the code consistent without changing a significant number of variables, functions, types, and comments.
> Rename folders to better match their content

- crates/modelardb_common/src/schemas.rs
- crates/modelardb_common/src/storage.rs
- crates/modelardb_server/src/optimizer/model_simple_aggregates.rs
- crates/modelardb_server/src/query/grid_exec.rs
- crates/modelardb_server/src/query/model_table.rs
- crates/modelardb_server/tests/integration_test.rs
This PR fixes #187 by storing `univariate_id` as `Int64Array` instead of `UInt64Array` as the [Delta](https://github.com/delta-io/delta-rs/issues/2175) [Lake](https://github.com/delta-io/delta-rs/issues/1751) [Protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types) does not support unsigned integers and #197 probably will not be resolved for some time. When reviewing this PR, please double check the necessary casts are performed everywhere they are needed. Currently, `UInt64Array` is reinterpreted as `Int64Array` when writing compressed segments to disk and `Int64Array` is reinterpreted as `UInt64Array` when data points are reconstructed from segments and aggregates are computed directly from the segments.
> Fix #187 by storing univariate_id as int64

- crates/modelardb_common/src/storage.rs
- crates/modelardb_server/src/storage/compressed_data_manager.rs
This PR prevents users from creating normal tables containing tables with columns for unsigned integers as Delta Lake does not support unsigned integers and [simply convert them to signed integers](https://docs.rs/delta_kernel/0.2.0/src/delta_kernel/engine/arrow_conversion.rs.html#163). So to remove this surprising behavior, is  support for unsigned integers removed for now. Due to the increasing amount of complexity caused by ModelarDB use of unsigned integers for some of the values in compressed segments and Delta Lake's lack of support for them, I have added a [comment](https://github.com/ModelarData/ModelarDB-RS/issues/197#issuecomment-2284776711) to #197 that we should look into using signed integers both in memory and on disk to remove the conversions and significantly reduce the …
> Disallow tables containing unsigned integers

- crates/modelardb_common/Cargo.toml
This PR makes `deltalake-core` explicitly use the `datafusion` feature for `deltalake-core` in `modelardb_common` as it is not enabled by default and it is not required for multiple of the methods we use from [`DeltaOps`](https://github.com/delta-io/delta-rs/blob/rust-v0.18.2/crates/core/src/operations/mod.rs#L154). It is technically not necessary to enable the feature for `modelardb_common` as it is already done for `modelardb_server`, thus it becomes enabled for all crates in ModelarDB as [Cargo unions features](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification). However, without enabling the `datafusion` feature for `deltalake-core` in `modelardb_common`, `modelardb_common` cannot be compiled outside of the ModelarDB project as it will fail with the confusing …
> Make deltalake-core explicitly use datafusion

- .github/workflows/cargo-build-lint-and-test-on-pr-and-push.yml
This PR updates the GitHub Action [upload-artifact](https://github.com/actions/upload-artifact) from v3 to v4 as v3 is [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
> Update upload-artifact as v3 is deprecated

- crates/modelardb_common/src/storage.rs
This PR will make `modelardbd` automatically create the local data folder if it does not exist instead of returning an error.
> Automatically create the local data folder

- crates/modelardb_server/src/storage/types.rs
This PR fixes the flaky `storage::types::tests::test_append_to_metric` test. Now we are checking if the timestamp is within 10 microseconds instead of exact to account for the time it takes it execute the `append()` function.
> Fixed flaky test_append_to_metric test

- .github/workflows/cargo-build-lint-and-test-on-pr-and-push.yml
- crates/modelardb_query/Cargo.toml
- crates/modelardb_server/Cargo.toml
This PR fixes #188 by replacing `macos-13` with `macos-latest` as the problem with unwinding failing in macOS is now fixed in [XCode](https://github.com/rust-lang/rust/issues/113783#issuecomment-1758036690) and rust-lang/rust/issues/113783 is closed as a result.
> Fix #188 by replacing macos-13 with -latest

- .gitignore
- Dockerfile
- docker-compose-cluster.yml
- docs/user/README.md
This PR fixes https://github.com/ModelarData/ModelarDB-RS/issues/235 by updating the Docker files to no longer create a service for PostgreSQL and to use the new structure for the command line arguments. Also, since the Docker is currently intended to be used for testing during development, the default built profile has been changed to `dev`.
> Updated Docker files to no longer use PostgreSQL

- docs/dev/README.md
- docs/user/README.md
This PR fixes #225 by updating the dev and user READMEs to make them consistent with the current implementation of `modelardbd`, `modelardm`, and `modelardb`. In addition, all of the text have been reordered so all lines have a length of 120 as that line length was used in most parts of the user README. Thus, the formatting of the two READMEs should now be consistent. When reviewing the changes, please look at how GitHub renders the READMEs to ensure they are easy to read when rendered.
> Update dev and user READMEs

- crates/modelardb_manager/src/remote.rs
- crates/modelardb_server/src/remote.rs
- crates/modelardb_server/tests/integration_test.rs
- crates/modelardb_storage/src/delta_lake.rs
- crates/modelardb_types/src/macros.rs
This PR adds a very simple action to the Apache Arrow Flight server for both the server and manager that can be used to "ping" the nodes and get the type of the node back. The action will always return `server` on the server and `manager` on the manager. The PR also includes an integration test for this new action on the server.
> Added NodeType action

- crates/modelardb_server/src/context.rs
- crates/modelardb_storage/src/metadata/table_metadata_manager.rs
This PR fixes https://github.com/ModelarData/ModelarDB-RS/issues/270 which caused cloud nodes to return an error when trying to query a table that was created while the cloud node was running.
The PR adds a new method to the table metadata manager that can be used to register the `model_table_name_tags` table which is the only metadata table required during querying. This new method is used to register the metadata table in the query data folder table metadata manager when a table is created.
The PR also adds unit tests for this new method since it is public.
> Fixed bug causing cloud nodes to return error when querying

- crates/modelardb_server/src/storage/uncompressed_data_manager.rs
- crates/modelardb_server/tests/integration_test.rs
- crates/modelardb_storage/src/lib.rs
- crates/modelardb_types/src/macros.rs
PR #275 showed that casts from `Any` to a concrete type is sometimes needed outside of extracting arrays from `Vec`s and `Recordbatch`es. Thus, this PR adds the `cast!()` macro which is defined as `$expr.as_any().downcast_ref::<$type>().unwrap()` and implements the `value!()` and `array!()` macros in terms of it. The PR also replaces all uses of `as_any().downcast_ref().unwrap()` found by `ripgrep`  with the macro.
> Add cast!() macro

- Cargo.toml
- crates/modelardb_client/Cargo.toml
- crates/modelardb_common/Cargo.toml
- crates/modelardb_common/src/arguments.rs
- crates/modelardb_common/src/test/data_generation.rs
- crates/modelardb_compression/Cargo.toml
- crates/modelardb_manager/Cargo.toml
- crates/modelardb_server/Cargo.toml
- crates/modelardb_storage/Cargo.toml
- crates/modelardb_types/Cargo.toml
This PR changes all crates from Rust Edition 2021 to Rust Edition 2024 which has been released as part of [Rust 1.85](https://blog.rust-lang.org/2025/02/20/Rust-1.85.0.html). This is done to prevent use of the new reserved syntax to minimize the overhead of upgrading later, enable use of [`async`](https://blog.rust-lang.org/2025/02/20/Rust-1.85.0.html#async-closures) [closures](https://rust-trends.com/posts/rust-s-async-closures/) to simplify writing `async` code, and allow [`let` chains](https://github.com/rust-lang/rust/pull/132833) to be used [when support for them is merged](https://github.com/rust-lang/rust/pull/132833#issuecomment-2580884688).
> Switch all crates from edition 2021 to 2024

- .github/workflows/build-lint-and-test.yml
- crates/modelardb_embedded/bindings/python/modelardb/__init__.py
- crates/modelardb_embedded/bindings/python/pyproject.toml
This PR updates the minimum Python version required for the bindings from 3.7 to 3.11. This was done because Python 3.7 is[ unsupported](https://devguide.python.org/versions/), because we already implicitly required [Python 3.10 as `match`](https://docs.python.org/3/whatsnew/3.10.html) was used, Python 3.11 is the [oldest Python version that does not require `typing-extensions`](https://docs.python.org/3/whatsnew/3.11.html) as a dependency, and Python 3.11 is the oldest version support by all three of the [GitHub Action `*-latest` runners](https://github.com/actions/runner-images/) as `macos-latest` only provides Python version 3.11, 3.12, and 3.13. In addition, the Python version used for GitHub Actions was also changed to Python 3.11, so the tests are run with the oldest version of …
> Upgrade Python version and remove typing_extensions

- crates/modelardb_common/src/test/data_generation.rs
- crates/modelardb_compression/src/types.rs
- crates/modelardb_embedded/bindings/python/modelardb/__init__.py
- crates/modelardb_embedded/bindings/python/tests/__init__.py
- crates/modelardb_embedded/src/capi.rs
- crates/modelardb_embedded/src/operations/client.rs
- crates/modelardb_embedded/src/operations/data_folder.rs
- crates/modelardb_embedded/src/operations/mod.rs
- crates/modelardb_server/src/storage/uncompressed_data_buffer.rs
- crates/modelardb_server/tests/integration_test.rs
This PR makes the naming more consistent in `modelardb_embedded` by using `source` instead of `from_modelardb` and `target` instead of `to_modelardb`. `ModelarDB` has also been changed to `Operations` in the Python bindings to make it consistent with the naming of the trait in the Rust API.
> Refactor naming in modelardb_embedded

- Cargo.lock
- crates/modelardb_client/Cargo.toml
- crates/modelardb_client/src/error.rs
- crates/modelardb_client/src/main.rs
- crates/modelardb_storage/src/delta_lake.rs
This PR fixes a bug in `modelardb_client` that prevents a relative path to a file with queries from being used. The problem was due to the use of `object_store` for local file paths as it explicitly does not allow [relative file paths](https://docs.rs/object_store/latest/object_store/path/struct.Path.html). Thus, it has been replaced with types from Rust's standard library. Like in #217, Rust's `Path` type is imported as `std::path::Path as StdPath` everywhere to keep the code consistent. Likewise, `PathBuf` is imported as `std::path::PathBuf as StdPathBuf` to be consistent with `Path`. In addition to fixing the bug, the PR also simplifies the code of `modelardb_client` as `object_store` could be removed. An additional check was also added to the simple command-line parameter parser to …
> Support relative paths in modelardb_client

- crates/modelardb_storage/src/metadata/table_metadata_manager.rs
- crates/modelardb_storage/src/metadata/time_series_table_metadata.rs
This PR fixes https://github.com/ModelarData/ModelarDB-RS/issues/253 which caused generated columns to have to be defined last in the schema. The bug was fixed by no longer using `TimeSeriesTableMetadata.is_field()` for checking the field when saving time series table metadata since `is_field()` only worked with `schema` and not `query_schema`.
`is_field()` has also been removed since it is no longer used.
> Fix bug that caused generated columns to have to be defined last in the schema

- crates/modelardb_bulkloader/src/main.rs
- crates/modelardb_embedded/bindings/python/modelardb/__init__.py
- crates/modelardb_server/tests/integration_test.rs
- crates/modelardb_storage/src/optimizer/model_simple_aggregates.rs
- crates/modelardb_storage/src/parser.rs
- crates/modelardb_storage/src/query/grid_exec.rs
- crates/modelardb_storage/src/query/normal_table.rs
This PR fixes a small bug in the Python bindings that was caused by the convenience functions not being imported in the `__init__.py` file from `operations.py`. With this PR it should now be possible to use both `modelardb.Operations.open_local()` and `modelardb.open_local()`.
Note that most of the changes are from Clippy issues. The relevant change that fixes the bug is in `crates/modelardb_embedded/bindings/python/modelardb/__init__.py`.
> Add missing imports for Python bindings

- crates/modelardb_compression/src/compression.rs
- crates/modelardb_compression/src/models/macaque_v.rs
- crates/modelardb_compression/src/models/mod.rs
- crates/modelardb_compression/src/models/timestamps.rs
- crates/modelardb_compression/src/types.rs
This PR implements MacaqueV, a lossy error-bounded single floating point compression method, as a replacement for Gorilla model type. Macaque adds two value preprocessing methods. 
First, MacaqueV rewrites a value by 1) replacing it with the previous one within the error bound or 2) rewriting the least mantissa bits of the value within the error bound so that Gorilla uses fewer bits for encoding. Then the value is encoded using the modified version of Gorilla. Gorilla's flag bits 0 and 10 are swapped to achieve better compression when used alongside PMC-Mean and Swing. 
Experiments using real-life datasets showed that MacaqueV improves ModelarDB's compression by 1.5-2.5x.
> Implement error-bounded lossy compression method MacaqueV 

- crates/modelardb_embedded/src/operations/client.rs
- crates/modelardb_manager/src/remote.rs
- crates/modelardb_server/src/configuration.rs
- crates/modelardb_server/src/context.rs
- crates/modelardb_server/src/manager.rs
- crates/modelardb_server/src/remote.rs
- crates/modelardb_server/tests/integration_test.rs
- crates/modelardb_test/src/table.rs
- crates/modelardb_types/src/flight/mod.rs
- crates/modelardb_types/src/flight/protocol.proto
- crates/modelardb_types/src/types.rs
This PR implements https://github.com/ModelarData/ModelarDB-RS/issues/338 to make the API more consistent and to avoid issues with partial table creation. 
Since the old `TableMetadata` protobuf message was used for the response in `InitializeDatabase` as well, this PR also changes the start up flow for cluster nodes to no longer use `InitializeDatabase`. Now edge nodes use the remote data folder to initialize the local data folder with potentially missing tables. This change has already been discussed as part of the discussion on how to remove the manager. Therefore, it was determined that it was simpler to just do it now, instead of having to implement a temporary workaround.
> Change CreateTables to CreateTable

- crates/modelardb_server/src/manager.rs
- crates/modelardb_types/src/types.rs
Closes #347 by changing the start up process for server nodes to check that the tables are identical if they have the same name. Previously we only checked the name which meant it was possible to start a server node with a table that was inconsistent with the cluster database schema.
Note that we purposely wait to create any tables until we have checked the local tables to ensure we do not create any tables before we know the local database is valid.
Currently we just return an error if there are tables in the local database that does not exist in the remote database. When reviewing, please consider whether we should change it so we just drop the local table instead.
> Fix bug making it possible to start a server with an inconsistent database schema

- crates/modelardb_embedded/bindings/python/modelardb/operations.py
- crates/modelardb_embedded/bindings/python/tests/test_operations.py
- crates/modelardb_embedded/src/capi.rs
- crates/modelardb_embedded/src/operations/client.rs
- crates/modelardb_embedded/src/operations/data_folder.rs
- crates/modelardb_embedded/src/operations/mod.rs
- crates/modelardb_manager/src/remote.rs
- crates/modelardb_server/src/configuration.rs
- crates/modelardb_server/src/context.rs
- crates/modelardb_server/src/remote.rs
- crates/modelardb_server/tests/integration_test.rs
- crates/modelardb_storage/src/delta_lake.rs
- crates/modelardb_storage/src/parser.rs
- crates/modelardb_types/src/flight/protocol.proto
- crates/modelardb_types/src/types.rs
Closes #343 by changing the parser to support the syntax `VACUUM table_name RETAIN num_seconds`. Note that `RETAIN` is optional. 
The PR also removes the previous method for setting the retention period which was through the environment variable `MODELARDBD_RETENTION_PERIOD_IN_SECONDS` and the configuration `retention_period_in_seconds`. This method was removed to avoid confusion between the two ways to set the retention period and since the setting was also only supposed to be used in the server (modelardbd). It could have been kept in the server but this might cause confusion on how it is handled in the manager and `Operations` API.
> Add support for setting retention period using RETAIN syntax

- crates/modelardb_compression/src/models/bits.rs
- crates/modelardb_manager/src/cluster.rs
- crates/modelardb_server/src/context.rs
- crates/modelardb_server/src/data_folders.rs
- crates/modelardb_server/src/manager.rs
- crates/modelardb_server/src/storage/uncompressed_data_manager.rs
- crates/modelardb_server/tests/integration_test.rs
- crates/modelardb_storage/src/lib.rs
- crates/modelardb_storage/src/metadata/table_metadata_manager.rs
- crates/modelardb_storage/src/parser.rs
- crates/modelardb_types/src/functions.rs
- crates/modelardb_types/src/types.rs
Closes https://github.com/ModelarData/ModelarDB-RS/issues/255 by updating all tests that use `is_err()` to instead check the specific error message. This ensures that the error messages are understandable and that we test for the correct errors.
> Check for specific error messages instead of just checking for errors
